### ISSUE TITLE
Hosting on github pages

### ISSUE THREAD

**Issue by gagangaur** [vivolscute/vivek_codes#2]
Hii @vivolscute why don't you host this on GitHub pages showcasing your work the effort you put in is a great thing to do😊

**Comment by viveks-codes** [comment]
ThanQ GaganBhai For Your kind Words😃. [https://vivolscute.github.io/](https://vivolscute.github.io/) it is already hosted 😊. I am Super new to Github. Looking Forward to work with you.- Vivek
